services:
  app:
    image: pretix/standalone:stable
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      - pretix:/data
      - ./pretix.cfg:/etc/pretix/pretix.cfg
    networks:
      - pretix

  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pretix
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - pretix

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - pretix

volumes:
  pretix:
  db:

networks:
  pretix:
